### ISSUE TITLE
Issue with turbo

### ISSUE THREAD

**Issue by oleteacher** [VolkanSah/ChatGPT-API-Integration-in-HTML-CSS-with-JS-PHP#9]
Nice job!

I try to use:

define('MODEL', 'gpt-3.5-turbo');

and get the following error in console:

```
script.js:27 
 Error: Unexpected response format 
{error: {…}}
error
: 
{message: 'This is a chat model and not supported in the v1/c…ndpoint. Did you mean to use v1/chat/completions?', type: 'invalid_request_error', param: 'model', code: null}
[[Prototype]]
: 
Object
constructor
```

**Comment by VolkanSah** [comment]
Hi Susanne,

I hope you're doing well. I saw your GitHub issue regarding an error you encountered while using a chatbot model in your code. After reviewing your code and the error message, it appears that the model you're using, 'gpt-3.5-turbo', is not supported by the OpenAI API for the V1/c endpoint. This is because the model is a chat model, and not suitable for the V1/c endpoint.

OpenAI offers a variety of models for different use cases, including chatbots. If you're looking to create a chatbot, I recommend selecting a supported chatbot model like Davinci, Curie, Ada, Babbage, or Codex.

It's also important to ensure that the selected model is suitable for the API version you're using. Please make sure you choose the correct API version and model for your application.

I hope this helps you solve the issue you encountered. If you have any further questions or concerns, please don't hesitate to reach out.

Best regards,

Volkan Sah

**Comment by oleteacher** [comment]
Thank you for the replay and information.

I had assumed that one could use with your chatgpt example with gpt-3.5-turbo after seeing this in your readme:

"Example for integration from GPT 3, 3.5 & 4 for your websites in HTML, CSS, JS & PHP"

Tried in your config.php:

```
<?php
// config file
define('OPENAI_API_KEY', 'sk-.................................');
define('MODEL', gpt-3.5-turbo');
define('TEMPERATURE', 0.9);
define('MAX_TOKENS', 1000);
define('TOP_P', 1);
define('FREQUENCY_PENALTY', 0.0);
define('PRESENCE_PENALTY', 0.0);
```

So, this was just misunderstanding with what was written in your readme. No biggie, just thought it would be worth asking about.

Thanks again.

**Comment by VolkanSah** [comment]
I update the readme.md with the endpoints

**Comment by oleteacher** [comment]
Oh yes, gave you a star!

I am doing something wrong it appears. My old brain is not grasping what you are providing:)

I have changed the following to use chatgpt-3.5-turbo:

`define('MODEL', 'gpt-3.5-turbo');`

Then:

`curl_setopt($ch, CURLOPT_URL, "https://api.openai.com/v1/chat/" . MODEL . "/completions");`

Not working, get this dev console error:

script.js:27  Error: Unexpected response format Objecterror: {message: 'Invalid URL (POST /v1/chat/gpt-3.5-turbo/completions)', type: 'invalid_request_error', param: null, code: null}[[Prototype]]: Object
(anonymous) @ script.js:27

**Comment by VolkanSah** [comment]
look for /v1/chat/completions than . Model.
use this curl_setopt($ch, CURLOPT_URL, "https://api.openai.com/v1/chat/completions"  ....  i will check it too, later. Must sleep :(

**Comment by VolkanSah** [comment]
It works well please adust to your needs! Here a guidline for how handel with security tipps
https://github.com/VolkanSah/ChatGPT-Security-Best-Practices
